# Generated by Django 5.0.6 on 2024-06-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_booking_occasion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='occasion',
            field=models.CharField(default='', max_length=200),
        ),
    ]
